/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;

import com.microsoft.sqlserver.jdbc.SQLServerDataSource;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import static javax.management.remote.JMXConnectorFactory.connect;
import java.sql.*;
import java.util.function.DoubleConsumer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author donam
 */
public class ManageBooks extends javax.swing.JFrame {
    Connection connect;
    /**
     * Creates new form ManageBooks
     */
    
    String maSach, tenSach, theLoai, tacGia, nhaXuatBan;
    int namXuatBan;
    float giaThanh;
    DefaultTableModel model;
    
    public ManageBooks() {
        initComponents();
        setBookDetailsToTable();
    }

    // to set the book details into the table
    public void setBookDetailsToTable() {
        
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=QLKS;"
                    + "encrypt=false";
                    
            String user="sa";
            String pass="1234";
            connect=DriverManager.getConnection(url, user, pass);
            Statement st = connect.createStatement();
            ResultSet rs = st.executeQuery("select * from DauSach");
            
            
            while(rs.next()) {
                String ma_sach = rs.getString("maSach");
                String ten_sach = rs.getString("tenSach");
                String the_loai = rs.getString("theLoai");
                String tac_gia = rs.getString("tacGia");
                String nha_xuat_ban = rs.getString("nhaXuatBan");
                int nam_xuat_ban = rs.getInt("namXuatBan");
                float gia_thanh = rs.getFloat("giaThanh");
                
                Object [] obj = {ma_sach, ten_sach, the_loai, tac_gia, 
                nha_xuat_ban, nam_xuat_ban, gia_thanh};
                model = (DefaultTableModel) tblBookDetails.getModel();
                model.addRow(obj);
                
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    //to add book to bookDetails table
    public boolean addBook() {
        boolean isAdded = false;
        maSach = txtMaSach.getText();
        tenSach = txtTenSach.getText();
        theLoai = txtTheLoai.getText();
        tacGia = txtTacGia.getText();
        nhaXuatBan = txtNhaXuatBan.getText();
        namXuatBan = Integer.parseInt(txtNamXuatBan.getText());
        giaThanh = Float.parseFloat(txtGiaThanh.getText());
        
        try {
            Connection connect = DBConnection.getConnection();
            
            String sql = "INSERT INTO DauSach(maSach, tenSach, theLoai, tacGia, "
                    + "nhaXuatBan, namXuatBan, giaThanh) VALUES(?,?,?,?,?,?,?)";
            
            PreparedStatement ps = connect.prepareStatement(sql);
            ps.setString(1, maSach);
            ps.setString(2, tenSach);
            ps.setString(3, theLoai);
            ps.setString(4, tacGia);
            ps.setString(5, nhaXuatBan);
            ps.setInt(6, namXuatBan);
            ps.setFloat(7, giaThanh);
            
            int rowCount = ps.executeUpdate();
            
            if(rowCount > 0) {
                isAdded = true;
            }
            else{
                isAdded = false;
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return isAdded;
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtTacGia = new javax.swing.JTextField();
        txtNhaXuatBan = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtNamXuatBan = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtGiaThanh = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtMaSach = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtTenSach = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtTheLoai = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        rSMaterialButtonRectangle1 = new rojerusan.RSMaterialButtonRectangle();
        rSMaterialButtonRectangle3 = new rojerusan.RSMaterialButtonRectangle();
        rSMaterialButtonRectangle4 = new rojerusan.RSMaterialButtonRectangle();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBookDetails = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(177, 8, 33));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(8, 177, 152));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 255));
        jLabel1.setText("BACK");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tác giả");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, -1, -1));

        txtTacGia.setBackground(new java.awt.Color(177, 8, 33));
        txtTacGia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTacGia.setForeground(new java.awt.Color(255, 255, 255));
        txtTacGia.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtTacGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTacGiaActionPerformed(evt);
            }
        });
        jPanel1.add(txtTacGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 420, 40));

        txtNhaXuatBan.setBackground(new java.awt.Color(177, 8, 33));
        txtNhaXuatBan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNhaXuatBan.setForeground(new java.awt.Color(255, 255, 255));
        txtNhaXuatBan.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtNhaXuatBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNhaXuatBanActionPerformed(evt);
            }
        });
        jPanel1.add(txtNhaXuatBan, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 430, 420, 40));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nhà xuất bản");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, -1, -1));

        txtNamXuatBan.setBackground(new java.awt.Color(177, 8, 33));
        txtNamXuatBan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNamXuatBan.setForeground(new java.awt.Color(255, 255, 255));
        txtNamXuatBan.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtNamXuatBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamXuatBanActionPerformed(evt);
            }
        });
        jPanel1.add(txtNamXuatBan, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 510, 420, 40));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Năm xuất bản");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 490, -1, -1));

        txtGiaThanh.setBackground(new java.awt.Color(177, 8, 33));
        txtGiaThanh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtGiaThanh.setForeground(new java.awt.Color(255, 255, 255));
        txtGiaThanh.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtGiaThanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGiaThanhActionPerformed(evt);
            }
        });
        jPanel1.add(txtGiaThanh, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 590, 420, 40));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Giá thành");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 570, -1, -1));

        txtMaSach.setBackground(new java.awt.Color(177, 8, 33));
        txtMaSach.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMaSach.setForeground(new java.awt.Color(255, 255, 255));
        txtMaSach.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtMaSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaSachActionPerformed(evt);
            }
        });
        jPanel1.add(txtMaSach, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 420, 40));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Mã sách");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, -1, -1));

        txtTenSach.setBackground(new java.awt.Color(177, 8, 33));
        txtTenSach.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTenSach.setForeground(new java.awt.Color(255, 255, 255));
        txtTenSach.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtTenSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenSachActionPerformed(evt);
            }
        });
        jPanel1.add(txtTenSach, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 420, 40));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Tên sách");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, -1));

        txtTheLoai.setBackground(new java.awt.Color(177, 8, 33));
        txtTheLoai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTheLoai.setForeground(new java.awt.Color(255, 255, 255));
        txtTheLoai.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtTheLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTheLoaiActionPerformed(evt);
            }
        });
        jPanel1.add(txtTheLoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 420, 40));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Thể loại");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, -1, -1));

        rSMaterialButtonRectangle1.setBackground(new java.awt.Color(8, 177, 152));
        rSMaterialButtonRectangle1.setText("XÓA");
        rSMaterialButtonRectangle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonRectangle1ActionPerformed(evt);
            }
        });
        jPanel1.add(rSMaterialButtonRectangle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 760, 120, 50));

        rSMaterialButtonRectangle3.setBackground(new java.awt.Color(8, 177, 152));
        rSMaterialButtonRectangle3.setText("THÊM");
        rSMaterialButtonRectangle3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonRectangle3ActionPerformed(evt);
            }
        });
        jPanel1.add(rSMaterialButtonRectangle3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 760, 120, 50));

        rSMaterialButtonRectangle4.setBackground(new java.awt.Color(8, 177, 152));
        rSMaterialButtonRectangle4.setText("SỬA");
        rSMaterialButtonRectangle4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonRectangle4ActionPerformed(evt);
            }
        });
        jPanel1.add(rSMaterialButtonRectangle4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 760, 120, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 930));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblBookDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sách", "Tên sách", "Thể loại", "Tác giả", "Nhà xuất bản", "Năm xuất bản", "Giá thành"
            }
        ));
        tblBookDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBookDetailsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBookDetails);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 1000, 610));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(8, 177, 152));
        jLabel2.setText("_________________________");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, -1, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(8, 177, 152));
        jLabel3.setText("QUẢN LÍ ĐẦU SÁCH");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 90, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 1160, 930));

        setSize(new java.awt.Dimension(1756, 940));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        HomePage home = new HomePage();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void txtTacGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTacGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTacGiaActionPerformed

    private void txtNhaXuatBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNhaXuatBanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNhaXuatBanActionPerformed

    private void txtNamXuatBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamXuatBanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamXuatBanActionPerformed

    private void txtGiaThanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGiaThanhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGiaThanhActionPerformed

    private void txtMaSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaSachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaSachActionPerformed

    private void txtTenSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenSachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenSachActionPerformed

    private void txtTheLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTheLoaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTheLoaiActionPerformed

    private void rSMaterialButtonRectangle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangle1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSMaterialButtonRectangle1ActionPerformed

    private void rSMaterialButtonRectangle3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangle3ActionPerformed

        if (addBook() == true) {
            JOptionPane.showMessageDialog(this, "Them thanh cong!");
            setBookDetailsToTable();
        }
        else {
            JOptionPane.showMessageDialog(this, "Them that bai!");
            
        }
    }//GEN-LAST:event_rSMaterialButtonRectangle3ActionPerformed

    private void rSMaterialButtonRectangle4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangle4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSMaterialButtonRectangle4ActionPerformed

    private void tblBookDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBookDetailsMouseClicked
        // TODO add your handling code here:
        int rowNo = tblBookDetails.getSelectedRow();
        TableModel model = tblBookDetails.getModel();
        
        txtMaSach.setText(model.getValueAt(rowNo, 0).toString());
        txtTenSach.setText(model.getValueAt(rowNo, 1).toString());
        txtTheLoai.setText(model.getValueAt(rowNo, 2).toString());
        txtTacGia.setText(model.getValueAt(rowNo, 3).toString());
        txtNhaXuatBan.setText(model.getValueAt(rowNo, 4).toString());
        txtNamXuatBan.setText(model.getValueAt(rowNo, 5).toString());
        txtGiaThanh.setText(model.getValueAt(rowNo, 6).toString());
        
    }//GEN-LAST:event_tblBookDetailsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageBooks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle1;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle3;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle4;
    private javax.swing.JTable tblBookDetails;
    private javax.swing.JTextField txtGiaThanh;
    private javax.swing.JTextField txtMaSach;
    private javax.swing.JTextField txtNamXuatBan;
    private javax.swing.JTextField txtNhaXuatBan;
    private javax.swing.JTextField txtTacGia;
    private javax.swing.JTextField txtTenSach;
    private javax.swing.JTextField txtTheLoai;
    // End of variables declaration//GEN-END:variables
}
